name: Build and Deploy to EC2

on:
  workflow_call:
    inputs:
      GITHUB_ENVIRONMENT:
        type: string
        description: 'Environment'
        required: true
        default: 'DEV'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.GITHUB_ENVIRONMENT }}
    outputs:
      image-tag: ${{ steps.build-step.outputs.image_tag }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ vars.CI_JAVA_VERSION }}

      - name: Build Maven project
        run: mvn clean package

      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        id: build-step
        run: |
          MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          GIT_SHORT_SHA=$(echo "${{ github.sha }}" | cut -c 1-8)
          IMAGE_VERSION="${MAVEN_VERSION}-${GIT_SHORT_SHA}"
          DOCKER_BUILDKIT=1 docker build . -t "sachinthadilshan/product:${IMAGE_VERSION}" \
            --build-arg ENV="${{ inputs.GITHUB_ENVIRONMENT }}" \
            --build-arg SERVICE="product"
          docker push "sachinthadilshan/product:${IMAGE_VERSION}"
          echo "image_tag=${IMAGE_VERSION}" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker Compose to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 13.53.129.105
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            set -e
            echo "Pulling the image sachinthadilshan/product:${{ needs.build.outputs.image-tag }} from Docker Hub..."
            docker pull sachinthadilshan/product:${{ needs.build.outputs.image-tag }}
            
            echo "Updating docker-compose file with the new image tag..."
            sed -i "s|image: sachinthadilshan/product:.*|image: sachinthadilshan/product:${{ needs.build.outputs.image-tag }}|g" docker-compose.yml
            
            echo "Restarting the containers with docker-compose..."
            docker-compose down
            docker-compose up -d
