name: CI [Manual] Product Info Integration

on:
  workflow_dispatch:

jobs:
  Test:
    uses: ./.github/workflows/test.yaml
    with:
      GITHUB_ENVIRONMENT: 'DEV'
    secrets: inherit

  Build:
    uses: ./.github/workflows/build.yaml
    with:
      GITHUB_ENVIRONMENT: 'DEV'
    secrets: inherit
    needs:
      - Test